name: Push Supabase DB Schema

on:
  push:
    branches: [main, dev]

jobs:
  push-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI (binary)
        run: |
          curl -L https://github.com/supabase/cli/releases/download/v1.160.0/supabase_1.160.0_linux_amd64.tar.gz -o supabase.tar.gz
          tar -xzf supabase.tar.gz
          sudo mv supabase /usr/local/bin
          supabase --version

      - name: Authenticate Supabase CLI
        run: |
          echo "${SUPABASE_ACCESS_TOKEN}" > ~/.supabase-access-token
          supabase login --token "$(cat ~/.supabase-access-token)"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Choose config based on branch
        id: set-config
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "config=.supabase/config.prd.toml" >> $GITHUB_OUTPUT
          else
            echo "config=.supabase/config.stg.toml" >> $GITHUB_OUTPUT
          fi

      - name: Push schema to Supabase
        run: |
          supabase db push --config ${{ steps.set-config.outputs.config }}